# Author: ISHAAN MALRA
# Program: B.TECH CSE, CC&VT
# Course: Container Orchestration and Infrastructure Automation
# SAP ID: 500082294
# ROLL NO: R214220536
# Batch: 5



# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /app

COPY . .

CMD [ "python", "client/client.py" ]
